window.HTMLEditor = window.HTMLEditor || {};

(function (ns) {

  ns.sampleHTML = [
    '<!DOCTYPE html>',
    '<html lang="zh-CN">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '<title>示例页面 - 点击元素开始编辑</title>',
    '<style>',
    '  body { font-family: "Microsoft YaHei", sans-serif; margin: 0; color: #333; background: #f7f8fa; }',
    '  header { background: #2f6fdb; color: #fff; padding: 28px 40px; }',
    '  header h1 { margin: 0 0 6px; font-size: 30px; }',
    '  header p { margin: 0; opacity: .85; }',
    '  main { padding: 24px 40px; max-width: 860px; }',
    '  .card { background: #fff; border-radius: 10px; padding: 20px 24px; margin-bottom: 18px; box-shadow: 0 1px 4px rgba(0,0,0,.06); }',
    '  .card h2 { margin-top: 0; font-size: 20px; color: #2f6fdb; }',
    '  .demo-img { border-radius: 8px; }',
    '  table { border-collapse: collapse; width: 100%; }',
    '  th, td { border: 1px solid #e3e6eb; padding: 8px 12px; text-align: left; }',
    '  th { background: #f0f3f8; }',
    '  footer { text-align: center; color: #9aa3b2; padding: 18px; font-size: 13px; }',
    '</style>',
    '</head>',
    '<body>',
    '<header>',
    '  <h1>欢迎使用 HTML 可视化编辑器</h1>',
    '  <p>在预览中单击任意元素即可选中并编辑，双击可直接修改文字</p>',
    '</header>',
    '<main>',
    '  <div class="card">',
    '    <h2>产品介绍</h2>',
    '    <p>这是一段示例文字。试试<b>双击这段话</b>直接修改文字内容，或者选中后用右侧属性面板调整字号、颜色与透明度。</p>',
    '    <img class="demo-img" src="data:image/svg+xml;charset=utf-8,%3Csvg xmlns=\'http://www.w3.org/2000/svg\' width=\'260\' height=\'160\'%3E%3Crect width=\'100%25\' height=\'100%25\' fill=\'%234d9fff\' rx=\'12\'/%3E%3Ctext x=\'50%25\' y=\'50%25\' fill=\'white\' font-size=\'26\' text-anchor=\'middle\' dominant-baseline=\'middle\' font-family=\'sans-serif\'%3E%E7%A4%BA%E4%BE%8B%E5%9B%BE%E7%89%87%3C/text%3E%3C/svg%3E" alt="示例图片" width="260" height="160">',
    '  </div>',
    '  <div class="card">',
    '    <h2>功能列表</h2>',
    '    <ul>',
    '      <li>点击选中元素，支持删除、复制、上移下移</li>',
    '      <li>修改文字、字号、字重、颜色、对齐、透明度</li>',
    '      <li>替换图片（链接或本地上传）</li>',
    '      <li>左侧源码与右侧预览实时双向同步</li>',
    '    </ul>',
    '  </div>',
    '  <div class="card">',
    '    <h2>数据示例</h2>',
    '    <table>',
    '      <tr><th>项目</th><th>数值</th></tr>',
    '      <tr><td>编辑器</td><td>HTML Editor</td></tr>',
    '      <tr><td>依赖</td><td>零依赖</td></tr>',
    '    </table>',
    '    <p>了解更多请访问 <a href="https://example.com" target="_blank">示例链接</a></p>',
    '  </div>',
    '</main>',
    '<footer>© 2026 示例页面 · 由 HTML 可视化编辑器提供</footer>',
    '<script>',
    '  // 默认情况下页面脚本不会执行，但会完整保留在导出的 HTML 中',
    '  console.log("示例脚本");',
    '<\/script>',
    '</body>',
    '</html>'
  ].join('\n');

})(window.HTMLEditor);
